apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/* # Path to dir where k8s manifests reside
build:
  local:
    push: false # Don't push local image builds to dockerhub, which is default behavior
  artifacts:
    - image: thewolverine/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync: # look for changes in file at
        manual:
          - src: 'src/**/*.ts'
            dest: .
    - image: thewolverine/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync: # look for changes in file at
        manual:
          - src: '**/*.js'
            dest: .
