apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-depl
spec:
  relicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      app: nats
  spec:
    containers:
      - name: nats
        image: nats-streaming:0.17.0
